# SPDX-FileCopyrightText: 2018-2026 Stichting DuckDB Foundation
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: MIT AND Apache-2.0
#
# Modified by Vane contributors.

from vane._native._sqltypes import (
    BIGINT as BIGINT,
    BIT as BIT,
    BLOB as BLOB,
    BOOLEAN as BOOLEAN,
    DATE as DATE,
    DOUBLE as DOUBLE,
    FLOAT as FLOAT,
    HUGEINT as HUGEINT,
    INTEGER as INTEGER,
    INTERVAL as INTERVAL,
    SMALLINT as SMALLINT,
    SQLNULL as SQLNULL,
    TIME as TIME,
    TIME_NS as TIME_NS,
    TIME_TZ as TIME_TZ,
    TIMESTAMP as TIMESTAMP,
    TIMESTAMP_MS as TIMESTAMP_MS,
    TIMESTAMP_NS as TIMESTAMP_NS,
    TIMESTAMP_S as TIMESTAMP_S,
    TIMESTAMP_TZ as TIMESTAMP_TZ,
    TINYINT as TINYINT,
    UBIGINT as UBIGINT,
    UHUGEINT as UHUGEINT,
    UINTEGER as UINTEGER,
    USMALLINT as USMALLINT,
    UTINYINT as UTINYINT,
    UUID as UUID,
    VARCHAR as VARCHAR,
    VARIANT as VARIANT,
    DuckDBPyType as DuckDBPyType,
)

__all__: list[str] = [
    "BIGINT",
    "BIT",
    "BLOB",
    "BOOLEAN",
    "DATE",
    "DOUBLE",
    "FLOAT",
    "HUGEINT",
    "INTEGER",
    "INTERVAL",
    "SMALLINT",
    "SQLNULL",
    "TIME",
    "TIME_NS",
    "TIMESTAMP",
    "TIMESTAMP_MS",
    "TIMESTAMP_NS",
    "TIMESTAMP_S",
    "TIMESTAMP_TZ",
    "TIME_TZ",
    "TINYINT",
    "UBIGINT",
    "UHUGEINT",
    "UINTEGER",
    "USMALLINT",
    "UTINYINT",
    "UUID",
    "VARCHAR",
    "VARIANT",
    "DuckDBPyType",
]
