[vane_runners][vane_runners]om [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] impo[vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners]o[vane_runners][vane_runners][vane_runners]io[vane_runners][vane_runners]

[vane_runners][vane_runners]om p[vane_runners][vane_runners]hlib impo[vane_runners][vane_runners] P[vane_runners][vane_runners]h

impo[vane_runners][vane_runners] py[vane_runners][vane_runners][vane_runners][vane_runners]

[vane_runners][vane_runners]om [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] impo[vane_runners][vane_runners] g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]i[vane_runners]


[vane_runners][vane_runners][vane_runners] g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners]([vane_runners]i[vane_runners]: [vane_runners][vane_runners][vane_runners], [vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]: i[vane_runners][vane_runners], [vane_runners][vane_runners]m[vane_runners]col[vane_runners]: i[vane_runners][vane_runners], [vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners]: i[vane_runners][vane_runners]):
    impo[vane_runners][vane_runners] [vane_runners][vane_runners]mpy [vane_runners][vane_runners] [vane_runners]p
    impo[vane_runners][vane_runners] p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners] p[vane_runners]
    impo[vane_runners][vane_runners] py[vane_runners][vane_runners][vane_runners]ow [vane_runners][vane_runners] p[vane_runners]
    impo[vane_runners][vane_runners] py[vane_runners][vane_runners][vane_runners]ow.p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners] p[vane_runners]pq
    [vane_runners][vane_runners]om [vane_runners][vane_runners]k[vane_runners][vane_runners] impo[vane_runners][vane_runners] F[vane_runners]k[vane_runners][vane_runners]

    # I[vane_runners]i[vane_runners]i[vane_runners]liz[vane_runners] F[vane_runners]k[vane_runners][vane_runners]
    F[vane_runners]k[vane_runners][vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners](0)  # Fo[vane_runners] [vane_runners][vane_runners]p[vane_runners]o[vane_runners][vane_runners]cibili[vane_runners]y
    [vane_runners][vane_runners]k[vane_runners] = F[vane_runners]k[vane_runners][vane_runners]()

    # G[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners]m[vane_runners]ll pool[vane_runners] o[vane_runners] [vane_runners][vane_runners]k[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners]h[vane_runners][vane_runners] w[vane_runners]'ll [vane_runners][vane_runners]mpl[vane_runners] [vane_runners][vane_runners]om
    POOL[vane_runners]SIZE = 1000  # Siz[vane_runners] o[vane_runners] i[vane_runners]i[vane_runners]i[vane_runners]l [vane_runners][vane_runners]k[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners] pool[vane_runners]

    # P[vane_runners][vane_runners]-g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners] pool[vane_runners]
    [vane_runners][vane_runners]m[vane_runners][vane_runners]pool = [[vane_runners][vane_runners]k[vane_runners].[vane_runners][vane_runners]m[vane_runners]() [vane_runners]o[vane_runners] [vane_runners] i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners](POOL[vane_runners]SIZE)]
    [vane_runners]m[vane_runners]il[vane_runners]pool = [[vane_runners][vane_runners]k[vane_runners].[vane_runners]m[vane_runners]il() [vane_runners]o[vane_runners] [vane_runners] i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners](POOL[vane_runners]SIZE)]
    comp[vane_runners][vane_runners]y[vane_runners]pool = [[vane_runners][vane_runners]k[vane_runners].comp[vane_runners][vane_runners]y() [vane_runners]o[vane_runners] [vane_runners] i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners](POOL[vane_runners]SIZE)]
    job[vane_runners]pool = [[vane_runners][vane_runners]k[vane_runners].job() [vane_runners]o[vane_runners] [vane_runners] i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners](POOL[vane_runners]SIZE)]
    [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]pool = [[vane_runners][vane_runners]k[vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]().[vane_runners][vane_runners]pl[vane_runners]c[vane_runners]("\[vane_runners]", ", ") [vane_runners]o[vane_runners] [vane_runners] i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners](POOL[vane_runners]SIZE)]

    # P[vane_runners][vane_runners]-g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners] pool[vane_runners]
    [vane_runners][vane_runners]c[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] = p[vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]g[vane_runners]([vane_runners][vane_runners][vane_runners]=p[vane_runners].Tim[vane_runners][vane_runners][vane_runners][vane_runners]mp.[vane_runners]ow(), p[vane_runners][vane_runners]io[vane_runners][vane_runners]=POOL[vane_runners]SIZE, [vane_runners][vane_runners][vane_runners]q="H")
    p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] = p[vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]g[vane_runners]([vane_runners][vane_runners][vane_runners]=p[vane_runners].Tim[vane_runners][vane_runners][vane_runners][vane_runners]mp.[vane_runners]ow(), p[vane_runners][vane_runners]io[vane_runners][vane_runners]=POOL[vane_runners]SIZE, [vane_runners][vane_runners][vane_runners]q="D")
    [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] = p[vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]g[vane_runners]([vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]=p[vane_runners].Tim[vane_runners][vane_runners][vane_runners][vane_runners]mp.[vane_runners]ow(), p[vane_runners][vane_runners]io[vane_runners][vane_runners]=POOL[vane_runners]SIZE, [vane_runners][vane_runners][vane_runners]q="D")

    [vane_runners][vane_runners][vane_runners][vane_runners] = {}
    [vane_runners]o[vane_runners] i i[vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners]([vane_runners][vane_runners]m[vane_runners]col[vane_runners]):
        col[vane_runners][vane_runners]yp[vane_runners] = i % 5

        i[vane_runners] col[vane_runners][vane_runners]yp[vane_runners] == 0:
            # I[vane_runners][vane_runners][vane_runners]g[vane_runners][vane_runners] col[vane_runners]m[vane_runners][vane_runners] (v[vane_runners]c[vane_runners]o[vane_runners]iz[vane_runners][vane_runners] op[vane_runners][vane_runners][vane_runners][vane_runners]io[vane_runners][vane_runners])
            [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] = i % 3
            i[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 0:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners]g[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners][vane_runners][vane_runners]i[vane_runners][vane_runners](0, 100, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 1:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"p[vane_runners]ic[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners][vane_runners][vane_runners]i[vane_runners][vane_runners](0, 1000, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]l[vane_runners][vane_runners]:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"vi[vane_runners]w[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners][vane_runners][vane_runners]i[vane_runners][vane_runners](0, 1000000, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])

        [vane_runners]li[vane_runners] col[vane_runners][vane_runners]yp[vane_runners] == 1:
            # Flo[vane_runners][vane_runners] col[vane_runners]m[vane_runners][vane_runners] (v[vane_runners]c[vane_runners]o[vane_runners]iz[vane_runners][vane_runners] op[vane_runners][vane_runners][vane_runners][vane_runners]io[vane_runners][vane_runners])
            [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] = i % 3
            i[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 0:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners][vane_runners]i[vane_runners]g[vane_runners]{i}"] = [vane_runners]p.[vane_runners]o[vane_runners][vane_runners][vane_runners]([vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners]i[vane_runners]o[vane_runners]m(0, 5, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]), 1)
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 1:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners]mp[vane_runners]{i}"] = [vane_runners]p.[vane_runners]o[vane_runners][vane_runners][vane_runners]([vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners]i[vane_runners]o[vane_runners]m(-20, 45, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]), 1)
            [vane_runners]l[vane_runners][vane_runners]:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"p[vane_runners][vane_runners]c[vane_runners][vane_runners][vane_runners][vane_runners]g[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners]o[vane_runners][vane_runners][vane_runners]([vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.[vane_runners][vane_runners]i[vane_runners]o[vane_runners]m(0, 100, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]), 2)

        [vane_runners]li[vane_runners] col[vane_runners][vane_runners]yp[vane_runners] == 2:
            # S[vane_runners][vane_runners]i[vane_runners]g col[vane_runners]m[vane_runners][vane_runners] ([vane_runners][vane_runners]mpli[vane_runners]g [vane_runners][vane_runners]om p[vane_runners][vane_runners]-g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] pool[vane_runners])
            [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] = i % 5
            i[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 0:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners]m[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([vane_runners][vane_runners]m[vane_runners][vane_runners]pool, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 1:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners]m[vane_runners]il[vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([vane_runners]m[vane_runners]il[vane_runners]pool, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 2:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"comp[vane_runners][vane_runners]y[vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners](comp[vane_runners][vane_runners]y[vane_runners]pool, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 3:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]pool, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]l[vane_runners][vane_runners]:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"job[vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners](job[vane_runners]pool, [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])

        [vane_runners]li[vane_runners] col[vane_runners][vane_runners]yp[vane_runners] == 3:
            # Bool[vane_runners][vane_runners][vane_runners] col[vane_runners]m[vane_runners][vane_runners] (v[vane_runners]c[vane_runners]o[vane_runners]iz[vane_runners][vane_runners] op[vane_runners][vane_runners][vane_runners][vane_runners]io[vane_runners][vane_runners])
            [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"i[vane_runners][vane_runners][vane_runners]c[vane_runners]iv[vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([T[vane_runners][vane_runners][vane_runners], F[vane_runners]l[vane_runners][vane_runners]], [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])

        [vane_runners]l[vane_runners][vane_runners]:
            # Tim[vane_runners][vane_runners][vane_runners][vane_runners]mp col[vane_runners]m[vane_runners][vane_runners] ([vane_runners][vane_runners]mpli[vane_runners]g [vane_runners][vane_runners]om p[vane_runners][vane_runners]-g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners]g[vane_runners][vane_runners])
            [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] = i % 3
            i[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 0:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners]c[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([vane_runners][vane_runners]c[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners], [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]li[vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]yp[vane_runners] == 1:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners](p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners], [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])
            [vane_runners]l[vane_runners][vane_runners]:
                [vane_runners][vane_runners][vane_runners][vane_runners][[vane_runners]"[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]{i}"] = [vane_runners]p.[vane_runners][vane_runners][vane_runners][vane_runners]om.choic[vane_runners]([vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners], [vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners])

    [vane_runners][vane_runners] = p[vane_runners].D[vane_runners][vane_runners][vane_runners]F[vane_runners][vane_runners]m[vane_runners]([vane_runners][vane_runners][vane_runners][vane_runners])
    p[vane_runners]pq.w[vane_runners]i[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]bl[vane_runners](
        [vane_runners][vane_runners]bl[vane_runners]=p[vane_runners].T[vane_runners]bl[vane_runners].[vane_runners][vane_runners]om[vane_runners]p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]([vane_runners][vane_runners]),
        wh[vane_runners][vane_runners][vane_runners]=[vane_runners]i[vane_runners],
        [vane_runners]ow[vane_runners]g[vane_runners]o[vane_runners]p[vane_runners][vane_runners]iz[vane_runners]=[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners] // [vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners],
    )
    p[vane_runners]i[vane_runners][vane_runners]([vane_runners]"Fi[vane_runners]i[vane_runners]h[vane_runners][vane_runners] w[vane_runners]i[vane_runners]i[vane_runners]g {[vane_runners]i[vane_runners]}")


SIZE[vane_runners]CONFIGS = [
    (10[vane_runners]000[vane_runners]000, 1),  # Lo[vane_runners][vane_runners] o[vane_runners] [vane_runners]ow[vane_runners], [vane_runners]i[vane_runners]gl[vane_runners] col
    (1[vane_runners]000[vane_runners]000, 32),  # B[vane_runners]l[vane_runners][vane_runners]c[vane_runners][vane_runners]
    (10[vane_runners]000, 1024),  # F[vane_runners]w [vane_runners]ow[vane_runners], m[vane_runners][vane_runners]y col[vane_runners]
]

ROWGROUP[vane_runners]CONFIGS = [1, 8, 64]

LOCAL[vane_runners]DATA[vane_runners]FIXTURE[vane_runners]PATH = P[vane_runners][vane_runners]h(g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]i[vane_runners]()) / "../../b[vane_runners][vane_runners]chm[vane_runners][vane_runners]ki[vane_runners]g/p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners]/loc[vane_runners]l[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]"


[vane_runners][vane_runners][vane_runners] g[vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners][vane_runners]m[vane_runners]i[vane_runners](p[vane_runners][vane_runners][vane_runners]m):
    ([vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners], [vane_runners][vane_runners]m[vane_runners]col[vane_runners]), [vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners] = p[vane_runners][vane_runners][vane_runners]m
    [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners]"{[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]}[vane_runners][vane_runners]ow[vane_runners][vane_runners]{[vane_runners][vane_runners]m[vane_runners]col[vane_runners]}[vane_runners]col[vane_runners][vane_runners]{[vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners]}[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners]"


@py[vane_runners][vane_runners][vane_runners][vane_runners].[vane_runners]ix[vane_runners][vane_runners][vane_runners][vane_runners](
    [vane_runners]cop[vane_runners]="[vane_runners][vane_runners][vane_runners][vane_runners]io[vane_runners]",
    p[vane_runners][vane_runners][vane_runners]m[vane_runners]=[([vane_runners]iz[vane_runners], [vane_runners]owg[vane_runners]o[vane_runners]p) [vane_runners]o[vane_runners] [vane_runners]iz[vane_runners] i[vane_runners] SIZE[vane_runners]CONFIGS [vane_runners]o[vane_runners] [vane_runners]owg[vane_runners]o[vane_runners]p i[vane_runners] ROWGROUP[vane_runners]CONFIGS],
    i[vane_runners][vane_runners]=l[vane_runners]mb[vane_runners][vane_runners] p[vane_runners][vane_runners][vane_runners]m: g[vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners][vane_runners]m[vane_runners]i[vane_runners](p[vane_runners][vane_runners][vane_runners]m),
)
[vane_runners][vane_runners][vane_runners] p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]il[vane_runners]([vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners]):
    ([vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners], [vane_runners][vane_runners]m[vane_runners]col[vane_runners]), [vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners] = [vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners].p[vane_runners][vane_runners][vane_runners]m
    [vane_runners]il[vane_runners]p[vane_runners][vane_runners]h = LOCAL[vane_runners]DATA[vane_runners]FIXTURE[vane_runners]PATH / [vane_runners]"[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]{[vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners]}[vane_runners]ow[vane_runners][vane_runners]{[vane_runners][vane_runners]m[vane_runners]col[vane_runners]}col[vane_runners][vane_runners]{[vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners]}g[vane_runners]o[vane_runners]p[vane_runners].p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners]"
    i[vane_runners] [vane_runners]o[vane_runners] [vane_runners]il[vane_runners]p[vane_runners][vane_runners]h.p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners].[vane_runners]xi[vane_runners][vane_runners][vane_runners]():
        [vane_runners]il[vane_runners]p[vane_runners][vane_runners]h.p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners].mk[vane_runners]i[vane_runners](p[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]=T[vane_runners][vane_runners][vane_runners])
    i[vane_runners] [vane_runners]o[vane_runners] [vane_runners]il[vane_runners]p[vane_runners][vane_runners]h.[vane_runners]xi[vane_runners][vane_runners][vane_runners]():
        g[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners]([vane_runners][vane_runners][vane_runners]([vane_runners]il[vane_runners]p[vane_runners][vane_runners]h), [vane_runners][vane_runners]m[vane_runners][vane_runners]ow[vane_runners], [vane_runners][vane_runners]m[vane_runners]col[vane_runners], [vane_runners][vane_runners]m[vane_runners][vane_runners]owg[vane_runners]o[vane_runners]p[vane_runners])
    [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners]([vane_runners]il[vane_runners]p[vane_runners][vane_runners]h)


@py[vane_runners][vane_runners][vane_runners][vane_runners].m[vane_runners][vane_runners]k.b[vane_runners][vane_runners]chm[vane_runners][vane_runners]k(g[vane_runners]o[vane_runners]p="[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners]loc[vane_runners]l")
[vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners](p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]il[vane_runners], b[vane_runners][vane_runners]chm[vane_runners][vane_runners]k):
    impo[vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners]

    [vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners]():
        [vane_runners][vane_runners] = [vane_runners][vane_runners][vane_runners][vane_runners].[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners](p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]il[vane_runners])
        [vane_runners][vane_runners][vane_runners][vane_runners][vane_runners][vane_runners] [vane_runners][vane_runners].[vane_runners]o[vane_runners][vane_runners][vane_runners][vane_runners]ow()

    b[vane_runners][vane_runners]chm[vane_runners][vane_runners]k([vane_runners][vane_runners][vane_runners][vane_runners][vane_runners]p[vane_runners][vane_runners]q[vane_runners][vane_runners][vane_runners])
