# SPDX-FileCopyrightText: 2018-2026 Stichting DuckDB Foundation
# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: MIT AND Apache-2.0
#
# Modified by Vane contributors.

import typing

class FunctionNullHandling:
    DEFAULT: typing.ClassVar[FunctionNullHandling]
    SPECIAL: typing.ClassVar[FunctionNullHandling]
    __members__: typing.ClassVar[dict[str, FunctionNullHandling]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class PythonUDFType:
    ARROW: typing.ClassVar[PythonUDFType]
    NATIVE: typing.ClassVar[PythonUDFType]
    __members__: typing.ClassVar[dict[str, PythonUDFType]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

ARROW: PythonUDFType
DEFAULT: FunctionNullHandling
NATIVE: PythonUDFType
SPECIAL: FunctionNullHandling
