# SPDX-FileCopyrightText: 2026 Vane contributors
# SPDX-License-Identifier: Apache-2.0

from typing import Any

def check_entry() -> None: ...

class DirectLimits:
    def __init__(self, window_bytes: int, frame_bytes: int, frame_rows: int, frame_slots: int) -> None: ...

class _TestSignal:
    def __init__(self) -> None: ...
    @property
    def count(self) -> int: ...

class DirectBatch:
    producer: str
    sequence: int
    @property
    def num_rows(self) -> int: ...
    def to_rows(self) -> list[tuple[Any, ...]]: ...
    def slice(self, offset: int, count: int) -> DirectBatch: ...
    def close(self) -> None: ...

class DirectChannel:
    def __init__(self, schema: bytes, limits: DirectLimits, producers: int, consumers: list[str]) -> None: ...
    def add_producer(self, producer: str) -> None: ...
    def seal_producers(self) -> None: ...
    def finish(self, producer: str, sequence: int) -> None: ...
    def abort(self, reason: str) -> None: ...
    def close_consumer(self, consumer: str) -> None: ...
    def poll(self, consumer: str, signal: _TestSignal | None = None) -> tuple[str, DirectBatch | None]: ...
    def _write_rows(
        self, producer: str, sequence: int, rows: list[tuple[Any, ...]], signal: _TestSignal | None = None
    ) -> str: ...
    def snapshot(self) -> dict[str, Any]: ...
    def producer_drained(self, producer: str) -> bool: ...

class TaskService:
    def __init__(self, connection: Any) -> None: ...
    def prepare(
        self,
        task_id: str,
        payload: bytes,
        connection_snapshot: bytes,
        source_snapshot: bytes,
        assignments: dict[str, list[str]],
        inputs: dict[str, list[tuple[DirectChannel, str]]],
        outputs: list[dict[str, Any]],
    ) -> None: ...
    def start(self, task_id: str, token: str) -> None: ...
    def pump(self, steps: int) -> int: ...
    def cancel(self, reason: str) -> None: ...
    def expire(self) -> bool: ...
    def release(self) -> None: ...
    def status(self) -> list[dict[str, Any]]: ...
